export {
  discoverRepositories,
  runCorpusExecution,
  generateCorrelationReport,
  classifyRepositories,
  generateFailureInventory,
  generateCorpusSummary,
  generateClassificationSummary,
  generateFailureInventorySummary,
} from './engine.js';

export type {
  RepositoryCorpusEntry,
  RepositoryCorpusIndex,
  CorpusExecutionResult,
  CorpusAggregateReport,
  AggregateMetrics,
  RepositoryCorrelationReport,
  FailureCorrelation,
  CorrelatedStructure,
  StructuralPattern,
  CompatibilityClassification,
  RepositoryClassification,
  ClassificationEvidence,
  FailureInventory,
  UnsupportedPattern,
  ReplayInstabilitySource,
  RiskyHealingStructure,
  ConfidenceCalibrationFailure,
  ParserLimitation,
  GovernanceWeakness,
  FrameworkType,
  LanguageType,
  BDDType,
  WrapperArchitecture,
  CorpusExecutionOptions,
} from './types.js';