/**
 * Healing domain models.
 *
 * HealingProposal is generated by a HealingStrategy when a locator fails.
 * HealingHistoryEntry records what happened during a healing cycle.
 * StrategyVerdict is the deterministic outcome of evaluating a proposal.
 */

export interface HealingStrategy {
  name: string;
  description: string;
  /** Priority order (lower = tried first). */
  priority: number;
  /** Minimum confidence threshold (0-1) to accept. */
  minConfidence: number;
}

export interface HealingProposal {
  id: string;
  /** The failing locator's ID. */
  locatorId: string;
  /** Original locator expression. */
  originalExpression: string;
  /** Proposed replacement expression. */
  proposedExpression: string;
  /** Strategy that generated this proposal. */
  strategy: string;
  /** Confidence score (0-1). */
  confidence: number;
  /** Evidence used to generate the proposal. */
  evidence: string[];
  /** Whether this proposal passed validation. */
  validated: boolean;
  /** Validation result details. */
  validationResult?: StrategyVerdict;
}

export interface StrategyVerdict {
  proposalId: string;
  /** Did the proposed locator resolve? */
  resolved: boolean;
  /** How many elements matched (0 = failure, >1 = ambiguous). */
  matchCount: number;
  /** The element text if matched. */
  matchedText?: string;
  /** Confidence after validation (0-1). */
  postValidationConfidence: number;
  /** Error message if validation failed. */
  error?: string;
}

export interface HealingHistoryEntry {
  id: string;
  /** The trace that triggered healing. */
  traceId: string;
  /** The locator that failed. */
  locatorId: string;
  /** Proposals generated (ordered by confidence). */
  proposals: HealingProposal[];
  /** Which proposal was selected (null if none). */
  selectedProposalId?: string;
  /** Was healing successful? */
  success: boolean;
  /** Timestamp. */
  timestamp: number;
  /** Reference to patch ID if one was applied. */
  patchId?: string;
}
